workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"


variables:
  ROS_DISTROS: noetic,foxy,humble,iron,rolling


stages:
  - ROS 1 Noetic
  - ROS 2 Foxy
  - ROS 2 Humble
  - ROS 2 Iron
  - ROS 2 Rolling


ros-noetic-ros-core:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-ros-core.yml
    strategy: depend

ros-noetic-ros-base:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-ros-base.yml
    strategy: depend

ros-noetic-robot:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-robot.yml
    strategy: depend

ros-noetic-perception:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-robot
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-perception.yml
    strategy: depend

ros-noetic-desktop:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-perception
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-desktop.yml
    strategy: depend

ros-noetic-desktop-full:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-desktop
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-desktop-full.yml
    strategy: depend


ros2-foxy-ros-core:
  stage: ROS 2 Foxy
  rules:
    - if: $ROS_DISTROS =~ /.*foxy.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-foxy/ros2-foxy-ros-core.yml
    strategy: depend

ros2-foxy-ros-base:
  stage: ROS 2 Foxy
  rules:
    - if: $ROS_DISTROS =~ /.*foxy.*/
  needs:
    - job: ros2-foxy-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-foxy/ros2-foxy-ros-base.yml
    strategy: depend

ros2-foxy-desktop:
  stage: ROS 2 Foxy
  rules:
    - if: $ROS_DISTROS =~ /.*foxy.*/
  needs:
    - job: ros2-foxy-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-foxy/ros2-foxy-desktop.yml
    strategy: depend


ros2-humble-ros-core:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-ros-core.yml
    strategy: depend

ros2-humble-ros-base:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-ros-base.yml
    strategy: depend

ros2-humble-perception:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-perception.yml
    strategy: depend

ros2-humble-desktop:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-perception
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-desktop.yml
    strategy: depend

ros2-humble-desktop-full:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-desktop
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-desktop-full.yml
    strategy: depend


ros2-iron-ros-core:
  stage: ROS 2 Iron
  rules:
    - if: $ROS_DISTROS =~ /.*iron.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-iron/ros2-iron-ros-core.yml
    strategy: depend

ros2-iron-ros-base:
  stage: ROS 2 Iron
  rules:
    - if: $ROS_DISTROS =~ /.*iron.*/
  needs:
    - job: ros2-iron-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-iron/ros2-iron-ros-base.yml
    strategy: depend

ros2-iron-perception:
  stage: ROS 2 Iron
  rules:
    - if: $ROS_DISTROS =~ /.*iron.*/
  needs:
    - job: ros2-iron-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-iron/ros2-iron-perception.yml
    strategy: depend

ros2-iron-desktop:
  stage: ROS 2 Iron
  rules:
    - if: $ROS_DISTROS =~ /.*iron.*/
  needs:
    - job: ros2-iron-perception
      optional: true
  trigger:
    include: .gitlab-ci/ros2-iron/ros2-iron-desktop.yml
    strategy: depend

ros2-iron-desktop-full:
  stage: ROS 2 Iron
  rules:
    - if: $ROS_DISTROS =~ /.*iron.*/
  needs:
    - job: ros2-iron-desktop
      optional: true
  trigger:
    include: .gitlab-ci/ros2-iron/ros2-iron-desktop-full.yml
    strategy: depend


ros2-rolling-ros-core:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-ros-core.yml
    strategy: depend

ros2-rolling-ros-base:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs:
    - job: ros2-rolling-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-ros-base.yml
    strategy: depend

ros2-rolling-desktop:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs:
    - job: ros2-rolling-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-desktop.yml
    strategy: depend
