workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG


variables:
  ROS_DISTROS:
    value: noetic,humble,jazzy,rolling
    description: Comma-separated list of ROS Distributions to build [noetic,humble,jazzy,rolling]


stages:
  - ROS 1 Noetic
  - ROS 2 Humble
  - ROS 2 Jazzy
  - ROS 2 Rolling
  - Postprocessing


ros-noetic-ros-core:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-ros-core.yml
    strategy: depend

ros-noetic-ros-base:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-ros-base.yml
    strategy: depend

ros-noetic-desktop-full:
  stage: ROS 1 Noetic
  rules:
    - if: $ROS_DISTROS =~ /.*noetic.*/
  needs:
    - job: ros-noetic-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros-noetic/ros-noetic-desktop-full.yml
    strategy: depend


ros2-humble-ros-core:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-ros-core.yml
    strategy: depend

ros2-humble-ros-base:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-ros-base.yml
    strategy: depend

ros2-humble-desktop-full:
  stage: ROS 2 Humble
  rules:
    - if: $ROS_DISTROS =~ /.*humble.*/
  needs:
    - job: ros2-humble-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-humble/ros2-humble-desktop-full.yml
    strategy: depend


ros2-jazzy-ros-core:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-jazzy/ros2-jazzy-ros-core.yml
    strategy: depend

ros2-jazzy-ubuntu22-ros-core:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-jazzy-ubuntu22/ros2-jazzy-ubuntu22-ros-core.yml
    strategy: depend

ros2-jazzy-ros-base:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs:
    - job: ros2-jazzy-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-jazzy/ros2-jazzy-ros-base.yml
    strategy: depend

ros2-jazzy-ubuntu22-ros-base:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs:
    - job: ros2-jazzy-ubuntu22-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-jazzy-ubuntu22/ros2-jazzy-ubuntu22-ros-base.yml
    strategy: depend

ros2-jazzy-desktop-full:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs:
    - job: ros2-jazzy-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-jazzy/ros2-jazzy-desktop-full.yml
    strategy: depend

ros2-jazzy-ubuntu22-desktop-full:
  stage: ROS 2 Jazzy
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/
  needs:
    - job: ros2-jazzy-ubuntu22-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-jazzy-ubuntu22/ros2-jazzy-ubuntu22-desktop-full.yml
    strategy: depend

post-ros2-jazzy-desktop-full:
  stage: Postprocessing
  rules:
    - if: $ROS_DISTROS =~ /.*jazzy.*/ && $CI_COMMIT_TAG
  needs:
    - job: ros2-jazzy-desktop-full
      optional: true
    - job: ros2-jazzy-ubuntu22-desktop-full
      optional: true
  trigger:
    include: .gitlab-ci/postprocessing/ros2-jazzy-desktop-full.yml
    strategy: depend

ros2-rolling-ros-core:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs: []
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-ros-core.yml
    strategy: depend

ros2-rolling-ros-base:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs:
    - job: ros2-rolling-ros-core
      optional: true
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-ros-base.yml
    strategy: depend

ros2-rolling-desktop-full:
  stage: ROS 2 Rolling
  rules:
    - if: $ROS_DISTROS =~ /.*rolling.*/
  needs:
    - job: ros2-rolling-ros-base
      optional: true
  trigger:
    include: .gitlab-ci/ros2-rolling/ros2-rolling-desktop-full.yml
    strategy: depend
