stages:
  - Image Variations


plain:
  stage: Image Variations
  trigger:
    include: .gitlab-ci/ml-variations/ros.yml
    strategy: depend
  rules:
  - if: $DISABLE_PLAIN == 'true'
    when: never
  - when: on_success

cuda:
  stage: Image Variations
  trigger:
    include: .gitlab-ci/ml-variations/ros-cuda.yml
    strategy: depend
  rules:
  - if: $DISABLE_CUDA == 'true'
    when: never
  - when: on_success

tensorrt:
  stage: Image Variations
  trigger:
    include: .gitlab-ci/ml-variations/ros-tensorrt.yml
    strategy: depend
  rules:
  - if: $DISABLE_TENSORRT == 'true'
    when: never
  - when: on_success

triton:
  stage: Image Variations
  needs:
    - job: cuda
      optional: true
  trigger:
    include: .gitlab-ci/ml-variations/ros-triton.yml
    strategy: depend
  rules:
  - if: $DISABLE_TRITON == 'true'
    when: never
  - when: on_success

torch:
  stage: Image Variations
  needs:
    - job: tensorrt
      optional: true
  trigger:
    include: .gitlab-ci/ml-variations/ros-torch.yml
    strategy: depend
  rules:
  - if: $DISABLE_TORCH == 'true'
    when: never
  - when: on_success

tf:
  stage: Image Variations
  needs:
    - job: tensorrt
      optional: true
  trigger:
    include: .gitlab-ci/ml-variations/ros-tf.yml
    strategy: depend
  rules:
  - if: $DISABLE_TF == 'true'
    when: never
  - when: on_success

ml:
  stage: Image Variations
  needs:
    - job: torch
      optional: true
  trigger:
    include: .gitlab-ci/ml-variations/ros-ml.yml
    strategy: depend
  rules:
  - if: $DISABLE_ML == 'true'
    when: never
  - when: on_success
