variables:
  UBUNTU_VERSION: "24.04"
  _TRITON_VERSION: 2.52.0
  DISABLE_CUDA_ARM64: "true"
  DISABLE_TENSORRT_ARM64: "true"
  DISABLE_TORCH_ARM64: "true"
  DISABLE_TF_ARM64: "true"
  DISABLE_ML_ARM64: "true"
