include: .gitlab-ci/ml-variations/ros.yml

variables:
  IMAGE_TYPE:       cuda
  BASE_IMAGE_TYPE:  "-cuda"
  IMAGE_REPO:       ${IMAGE_BASE}/${ROS_VERSION_NAME}-cuda
  IMAGE_REPO_CI:    ${IMAGE_BASE_CI}/${ROS_VERSION_NAME}-cuda
