include:
  - .gitlab-ci/ml-variations/ros-cuda-trt.yml
  - .gitlab-ci/ml-variations/.torch.yml
  - .gitlab-ci/ml-variations/.tf.yml

variables:
  IMAGE_REPO:               ${IMAGE_BASE}/${ROS_VERSION_NAME}-ml
  IMAGE_REPO_CI:            ${IMAGE_BASE_CI}/${ROS_VERSION_NAME}-ml
  IMAGE_CI_CACHE:           ${IMAGE_BASE_CI}/${ROS_VERSION_NAME}-torch:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}-torch${TORCH_VERSION}_ci
  TAG:                      ${ROS_DISTRO}-${ROS_PACKAGE}-tf${TF_VERSION}-torch${TORCH_VERSION}
