include:
  - .gitlab-ci/ml-variations/ros-cuda.yml
  - .gitlab-ci/ml-variations/.torch.yml

variables:
  IMAGE_REPO:               ${IMAGE_BASE}/ros${ROS_VERSION}-torch
  TAG:                      ${ROS_DISTRO}-${ROS_PACKAGE}-torch${TORCH_VERSION}
  TAG_DEFAULT_ROS_PACKAGE:  ${ROS_DISTRO}-torch${TORCH_VERSION}
  IMAGE_CI_CACHE:           ${IMAGE_BASE}/ros${ROS_VERSION}-cuda:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}_ci
