include:
  - .gitlab-ci/ml-variations/ros-cuda.yml
  - .gitlab-ci/ml-variations/.torch.yml
  - .gitlab-ci/ml-variations/.tf.yml

variables:
  IMAGE_REPO:               ${IMAGE_BASE}/ros${ROS_VERSION}-ml
  IMAGE_CI_CACHE:           ${IMAGE_BASE}/ros${ROS_VERSION}-torch:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}-torch${TORCH_VERSION}_ci
  TAG:                      ${ROS_DISTRO}-${ROS_PACKAGE}-tf${TF_VERSION}-torch${TORCH_VERSION}
  TAG_DEFAULT_ROS_PACKAGE:  ${ROS_DISTRO}-tf${TF_VERSION}-torch${TORCH_VERSION}