include:
  - .gitlab-ci/ml-variations/ros.yml
  - .gitlab-ci/ml-variations/.triton.yml

variables:
  IMAGE_TYPE:         "triton"
  BASE_IMAGE_TYPE:    ""
  IMAGE_REPO_SUFFIX:  "ros2-${IMAGE_TYPE}"
  IMAGE_REPO:         "${IMAGE_BASE}/${IMAGE_REPO_SUFFIX}"
  IMAGE_REPO_CI:      "${IMAGE_BASE_CI}/${IMAGE_REPO_SUFFIX}"
  IMAGE_CI_CACHE:     "${IMAGE_BASE_CI}/ros2:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}_ci"
  TAG:                "${ROS_DISTRO}-${ROS_PACKAGE}-triton${TRITON_VERSION}"
