include:
  - .gitlab-ci/ml-variations/ros-tensorrt.yml
  - .gitlab-ci/ml-variations/.torch.yml

variables:
  IMAGE_TYPE:         "torch"
  BASE_IMAGE_TYPE:    "-tensorrt"
  IMAGE_REPO_SUFFIX:  "ros2-${IMAGE_TYPE}"
  IMAGE_REPO:         "${IMAGE_BASE}/${IMAGE_REPO_SUFFIX}"
  IMAGE_REPO_CI:      "${IMAGE_BASE_CI}/${IMAGE_REPO_SUFFIX}"
  TAG:                "${ROS_DISTRO}-${ROS_PACKAGE}-torch${TORCH_VERSION}"
  IMAGE_CI_CACHE:     "${IMAGE_BASE_CI}/ros2-tensorrt:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}_ci"
