include:
  - .gitlab-ci/ml-variations/ros.yml
  - .gitlab-ci/ml-variations/.triton.yml

variables:
  IMAGE_TYPE:       triton
  IMAGE_REPO:       ${IMAGE_BASE}/${ROS_VERSION_NAME}-triton
  IMAGE_REPO_CI:    ${IMAGE_BASE_CI}/${ROS_VERSION_NAME}-triton
  IMAGE_CI_CACHE:   ${IMAGE_BASE_CI}/${ROS_VERSION_NAME}:${CI_COMMIT_REF_SLUG}_${ROS_DISTRO}-${ROS_PACKAGE}_ci
  TAG:              ${ROS_DISTRO}-${ROS_PACKAGE}-triton${TRITON_VERSION}
