include: .gitlab-ci/ml-variations/.template.yml

variables:
  IMAGE_TYPE:         "plain"
  BASE_IMAGE_TYPE:    ""
  IMAGE_REPO_SUFFIX:  "ros2"
  IMAGE_REPO:         "${IMAGE_BASE}/${IMAGE_REPO_SUFFIX}"
  IMAGE_REPO_CI:      "${IMAGE_BASE_CI}/${IMAGE_REPO_SUFFIX}"
  TAG:                "${ROS_DISTRO}-${ROS_PACKAGE}"
  IMAGE:              "${IMAGE_REPO}:${TAG}"
  IMAGE_CI:           "${IMAGE_REPO_CI}:${CI_COMMIT_REF_SLUG}_${TAG}_ci"
  IMAGE_CI_CACHE:     "${IMAGE_CI}"
